name: CI - test & build
on: [push, pull_request]
jobs:
  #TODO - lint!
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Test
        run: go test -v ./internal/*/

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: --snapshot #release --rm-dist
#        env:
#          GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
