name: CI - release
on:
  push:
    tags:
      - '*'
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 #required for the changelog to work correctly
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist #--snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
